### ISSUE TITLE
Stage 4 Criteria

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-arraybuffer-transfer#12]
- [x] Tests merged
 - [x] Implementations
   - [x] v8: https://chromium-review.googlesource.com/c/v8/v8/+/4166662 (in v114)
   - [x] sm: https://bugzilla.mozilla.org/show_bug.cgi?id=1841113 (v117, behind a flag) https://bugzilla.mozilla.org/show_bug.cgi?id=1865103 (tracking unflagging) - unflagged in v122
   - [x] jsc: https://github.com/WebKit/WebKit/pull/20087 (merged but not yet released unflagged)
   - [x] serenity (their site claims test262 passes: https://serenityos.github.io/libjs-website/test262/per-file/?path=test/built-ins/ArrayBuffer/prototype)
   - [x] es-shims: https://npmjs.com/arraybuffer.prototype.transfer / https://npmjs.com/arraybuffer.prototype.transfertofixedlength / https://npmjs.com/arraybuffer.prototype.detached
 - [x] [spec PR](https://github.com/tc39/ecma262/pull/3175)
   - [x] editor-approved
 - [x] consensus

**Comment by bakkot** [comment]
JSC has landed the feature: https://github.com/WebKit/WebKit/pull/20087

Not sure when it will hit stable Safari though.
